name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - run: npm run build
      - run: |
          echo @lablnet:https://npm.pkg.github.com/ > public/.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> public/.npmrc
      - run: npm publish
        working-directory: ./public
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
